### ISSUE TITLE
Nice Job

### ISSUE THREAD

**Issue by sanjeevyadavIT** [lokeshbisht/Android-Games-Automation#1]
Hi lokesh, its great seeing you working on all these projects and using github, What is this project about?  & let me know if you need any help regarding maintaining open source project or anything. Would be happy to help 😀 

And I hope you are safe among current crisis, 

PS: I know this is not the best place to chat 😅

**Comment by lokeshbisht** [comment]
> 
> 
> Hi lokesh, its great seeing you working on all these projects and using github, What is this project about? & let me know if you need any help regarding maintaining open source project or anything. Would be happy to help 😀
> 
> And I hope you are safe among current crisis,
> 
> PS: I know this is not the best place to chat 😅

Sir, in this project, I am using adb and python to automate simple android games.

Sir I would definitely ask you whenever I am stuck.

I am good sir. And what about you? Working from home or what?

**Comment by sanjeevyadavIT** [comment]
> Sir I would definitely ask you whenever I am stuck.

Sure, let me know.

> And what about you? Working from home or what?

Yes, working from home :)
